const express = require('express');
const nodemailer = require('nodemailer');
const { requireAuth } = require('../middleware/auth');
const fs = require('fs');
const path = require('path');

const router = express.Router();

const USERS_FILE = path.join(__dirname, '../data/users.json');

function loadUsers() {
  if (!fs.existsSync(USERS_FILE)) return [];
  try { return JSON.parse(fs.readFileSync(USERS_FILE, 'utf8')); } catch { return []; }
}

// Create a reusable transporter.
// Uses environment variables so production credentials never live in code.
// For development, configure SMTP_HOST=smtp.ethereal.email (free test SMTP)
// or set USE_ETHEREAL=true to auto-generate a test account.
async function getTransporter() {
  if (process.env.USE_ETHEREAL === 'true' || !process.env.SMTP_HOST) {
    // Auto-create a free Ethereal test account for development
    const testAccount = await nodemailer.createTestAccount();
    const transporter = nodemailer.createTransport({
      host: 'smtp.ethereal.email',
      port: 587,
      secure: false,
      auth: { user: testAccount.user, pass: testAccount.pass }
    });
    return { transporter, isTest: true };
  }

  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS
    }
  });
  return { transporter, isTest: false };
}

// ── POST /api/resume/email ────────────────────────────────────────────────────
// Sends a PDF URL to the authenticated user's registered email address.
router.post('/', requireAuth, async (req, res) => {
  const { pdf_url, subject, message } = req.body;

  if (!pdf_url) {
    return res.status(400).json({ error: 'pdf_url is required' });
  }

  // Resolve the user's email from their profile
  const users = loadUsers();
  const user = users.find(u => u.id === req.userId);
  if (!user) return res.status(404).json({ error: 'User not found' });

  const toEmail = req.body.email || user.email;

  try {
    const { transporter, isTest } = await getTransporter();

    const info = await transporter.sendMail({
      from: process.env.SMTP_FROM || '"ResumeForge" <noreply@resumeforge.app>',
      to: toEmail,
      subject: subject || 'Your Resume from ResumeForge',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px;">
          <h2 style="color: #8B0000;">Your Resume is Ready</h2>
          <p>${message || 'Your tailored resume has been generated. Click the link below to download it.'}</p>
          <p>
            <a href="${pdf_url}"
               style="background: #8B0000; color: #fff; padding: 12px 24px; 
                      text-decoration: none; border-radius: 4px; display: inline-block;">
              Download PDF
            </a>
          </p>
          <p style="color: #999; font-size: 12px;">
            This link will expire in 24 hours. Generated by ResumeForge.
          </p>
        </div>
      `
    });

    const response = { success: true, messageId: info.messageId, sentTo: toEmail };

    // For Ethereal test emails, provide a preview URL
    if (isTest) {
      response.previewUrl = nodemailer.getTestMessageUrl(info);
      response.note = 'Development mode: email was not actually sent. Visit the previewUrl to see it.';
    }

    res.json(response);
  } catch (err) {
    res.status(500).json({ error: 'Failed to send email: ' + err.message });
  }
});

module.exports = router;
